server: 
  port: 8080
  tomcat: 
    uri-encoding: UTF-8
  servlet:
    session:
      timeout: 36000
spring: 
  datasource: 
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/medicine?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

mybatis: 
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.gackey.medicine.entity
  
medicine: 
  security: 
    browser: 
      loginPage: /login.html
      loginType: JSON
      rememberMeSeconds: 259200